### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by TrulyInfinite** [XcodersHub/TorrentLeechX#3]
When I run the gleech command, the file downloads well but it doesn't get uploaded to the cloud.

I checked the Heroku logs and I found this.

```
02-Oct-21 10:58:22 - ERROR - list index out of range [dispatcher.py:230]

2021-10-02T05:28:22.230242+00:00 app[worker.1]: Traceback (most recent call last):

2021-10-02T05:28:22.230243+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 217, in handler_worker

2021-10-02T05:28:22.230244+00:00 app[worker.1]:     await handler.callback(self.client, *args)

2021-10-02T05:28:22.230244+00:00 app[worker.1]:   File "/app/tobrot/plugins/incoming_message_fn.py", line 123, in incoming_message_f

2021-10-02T05:28:22.230245+00:00 app[worker.1]:     sagtus, err_message = await call_apropriate_function(

2021-10-02T05:28:22.230245+00:00 app[worker.1]:   File "/app/tobrot/helper_funcs/download_aria_p_n.py", line 257, in call_apropriate_function

2021-10-02T05:28:22.230245+00:00 app[worker.1]:     await upload_to_gdrive(

2021-10-02T05:28:22.230246+00:00 app[worker.1]:   File "/app/tobrot/helper_funcs/upload_to_tg.py", line 158, in upload_to_gdrive

2021-10-02T05:28:22.230246+00:00 app[worker.1]:     gUP = re.findall("\[(.*)\]", con)[0]

2021-10-02T05:28:22.230246+00:00 app[worker.1]: IndexError: list index out of range
```

Thanks.

**Comment by TrulyInfinite** [comment]
I'm now closing this issue. No solutions got :(

**Comment by dinesh-0602** [comment]
@TrulyInfinite Come to support group pls
